version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    container_name: cours
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: cours
      MYSQL_USER: jimmy
      MYSQL_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data: